### ISSUE TITLE
prefer performance.now to Date.now

### ISSUE THREAD

**Issue by nickdesaulniers** [sajjadt/simdjs-gl-matrix-bench#3]
as it's slightly higher resolution (microseconds vs milliseconds)

**Comment by sajjadt** [comment]
That would be a great addition, but, is it available in SpiderMonkey engine?

**Comment by nickdesaulniers** [comment]
yep, had it for years, should be in all major browsers now

**Comment by nickdesaulniers** [comment]
oh, it's probably a DOM binding in Gecko as opposed to a JS native fn in SpiderMonkey

**Comment by nickdesaulniers** [comment]
there's also console.time and console.timeEnd

**Comment by sajjadt** [comment]
For now I just keep the "index.html" in the benchmark removing the "run.js" script. So we can benefit from high resolution timers ;)
